name: CI MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos-build:
    name: build+test Node.js ${{ matrix.node-version }} on ${{ matrix.host }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: true
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        host: [macos-latest]
        # https://nodejs.org/api/n-api.html#node-api-version-matrix
        node-version: [18.17.0]
        zig-version: [master]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
      - run: npm install
      - name: Download Node.js ${{ matrix.node-version }} headers
        run: npm run headers
      - run: npm run build
      - run: npm test
